### ISSUE TITLE
Where are the local dependencies?

### ISSUE THREAD

**Issue by Oppodelldog** [openzipkin/zipkin-api-example#2]
It seems that there are some local packages missing.

Where can I find them, I was really happy to find that little sample code for go.

https://github.com/openzipkin/zipkin-api-example/blob/b1aded081b150f30c95b50344fc2e7eb14bfa2a3/go/post_sample_trace.go#L12

**Comment by codefromthecrypt** [comment]
The readme has command to generate these dependencies. They are generated
from the openapi/swagger file

**Comment by Oppodelldog** [comment]
Omg. Sorry for Not reading :-)
Thanks and have a nice weekend.

**Comment by codefromthecrypt** [comment]
thanks for trying this!
